### ISSUE TITLE
Bug: Tabellen rendern initial nicht

### ISSUE THREAD

**Issue by sdvg** [public-ui/kolibri#6949]
Reproduktion: Sample App öffnen und mit Pfeiltasten navigieren, bis eine Tabelle kommt, die nicht rendered.
z.B. hier: https://develop--kolibri-public-ui.netlify.app/#/table/sort-data
Nach Refresh sind die Tabellen sichtbar.

![screenshot 2024-10-21-14 31 51@2x](https://github.com/user-attachments/assets/e2498e43-f73e-4cfd-a4dc-53baf8072cfe)

Sichtbare Exception:

```
TypeError: Cannot read properties of undefined (reading 'reduce')
    at d.renderSpacer (1832.js:2:13182)
    at d.render (1832.js:2:14913)
    at Nn (main.js:2:175646)
    at main.js:2:175450
    at Generator.next (<anonymous>)
    at main.js:2:163244
    at new Promise (<anonymous>)
    at c (main.js:2:163063)
    at Cn (main.js:2:175108)
```

**Comment by sdvg** [comment]
Ebenfalls betroffen ist das erste Beispiel (vertical) auf dieser Seite:
https://develop--kolibri-public-ui.netlify.app/#/table/multi-sort

Dieses rendered auch nach einem Refresh nicht.
